stages:
    - code-analyze
    - cppcheck
    - clang
    - doxygen
    - building
    
CPPCHECK:
    stage: code-analyze
    image: ubuntu:bionic
    before_script:
        - apt update
        - apt install -y --no-install-recommends cppcheck
        - cppcheck --version
    script:
        - cppcheck src/*.cpp include/*.h --verbose --enable=all --inconclusive --check-config
        
# CLANG:
#     stage: code-analyze
#     image: archlinux/base
#     variables:
#         CC: clang
#         CXX: clang++
#     before_script:
#         - pacman -Syu --needed --noconfirm clang-tools-extra
#         - clang-tidy --version
#     script:
#         - clang-tidy src/*.cpp -warnings-as-errors="*" -checks="-",clang-analyzer-*
        
# BUILD_GCC:
#     stage: building
#     image: lasote/conangcc7
#     before_script:
#         - sudo apt-get update
#         - sudo apt-get install -y gcovr
#     script:
#         - mkdir -p build && cd build
#         - conan install ..
#         - cmake ..
#         - cmake --build .