stages:
    - cppcheck
    - clang
    
CPPCHECK:
    stage: cppcheck
    image: ubuntu:bionic
    before_script:
        - apt update
        - apt install -y --no-install-recommends cppcheck=1.82-1
        - cppcheck --version
    script:
        - cppcheck src/*.cpp --verbose --enable=all --inconclusive --check-config
        
CLANG:
    stage: clang
    image: archlinux/base
    variables:
        CC: clang
        CXX: clang++
    before_script:
        - pacman -Syu --needed --noconfirm clang-tools-extra=6.0.1-2
        - clang-tidy --version
    script:
        - clang-tidy -warnings-as-errors="*" -checks="-",clang-analyzer-*