dist: trusty
sudo: required
before_install:
  - sudo apt-get install g++
  - sudo apt-get install python-dev
  - sudo apt-get install zlib1g-dev
  - sudo apt-get install openssl libssl-dev
  - sudo apt-get install libpcap-dev

language: cpp
compiler:
  - g++

install:
  - sudo apt-get install -qq cppcheck
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.14.5/cmake-3.14.5.tar.gz
  - tar -xvf cmake-3.14.5.tar.gz > /dev/null
  - mv cmake-3.14.5 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  # run cmake; here we assume that the project's
  # top-level CMakeLists.txt is located at '..'
  - mkdir build
  - cd build
  - cmake ..

script:
  - cppcheck --quiet --error-exitcode=1 src/*.cpp
  # once CMake has done its job we just build using make as usual
  - make
  # if the project uses ctest we can run the tests like this
  - make test
